export const FLOWOPS_OWNER_ROLE_PERMISSIONS = [
    'agentflows:config',
    'agentflows:create',
    'agentflows:delete',
    'agentflows:domains',
    'agentflows:duplicate',
    'agentflows:export',
    'agentflows:import',
    'agentflows:update',
    'agentflows:view',
    'apikeys:create',
    'apikeys:delete',
    'apikeys:update',
    'apikeys:view',
    'auditLogs:view',
    'assistants:create',
    'assistants:delete',
    'assistants:update',
    'assistants:view',
    'chatflows:config',
    'chatflows:create',
    'chatflows:delete',
    'chatflows:domains',
    'chatflows:duplicate',
    'chatflows:export',
    'chatflows:import',
    'chatflows:update',
    'chatflows:view',
    'credentials:create',
    'credentials:delete',
    'credentials:share',
    'credentials:update',
    'credentials:view',
    'datasets:create',
    'datasets:delete',
    'datasets:update',
    'datasets:view',
    'documentStores:add-loader',
    'documentStores:create',
    'documentStores:delete',
    'documentStores:delete-loader',
    'documentStores:preview-process',
    'documentStores:update',
    'documentStores:upsert-config',
    'documentStores:view',
    'evaluations:create',
    'evaluations:delete',
    'evaluations:run',
    'evaluations:view',
    'evaluators:create',
    'evaluators:delete',
    'evaluators:update',
    'evaluators:view',
    'executions:delete',
    'executions:view',
    'loginActivity:view',
    'logs:view',
    'roles:manage',
    'sso:manage',
    'templates:custom',
    'templates:custom-delete',
    'templates:custom-share',
    'templates:flowexport',
    'templates:marketplace',
    'templates:toolexport',
    'tools:create',
    'tools:delete',
    'tools:export',
    'tools:update',
    'tools:view',
    'users:manage',
    'variables:create',
    'variables:delete',
    'variables:update',
    'variables:view',
    'workspace:add-user',
    'workspace:create',
    'workspace:delete',
    'workspace:export',
    'workspace:import',
    'workspace:unlink-user',
    'workspace:update',
    'workspace:view'
]

export const FLOWOPS_ADMIN_ROLE_PERMISSIONS = FLOWOPS_OWNER_ROLE_PERMISSIONS.filter(
    (permission) => !['sso:manage', 'logs:view'].includes(permission)
)

export const FLOWOPS_MEMBER_ROLE_PERMISSIONS = [
    'agentflows:config',
    'agentflows:create',
    'agentflows:duplicate',
    'agentflows:export',
    'agentflows:import',
    'agentflows:update',
    'agentflows:view',
    'assistants:create',
    'assistants:update',
    'assistants:view',
    'chatflows:config',
    'chatflows:create',
    'chatflows:duplicate',
    'chatflows:export',
    'chatflows:import',
    'chatflows:update',
    'chatflows:view',
    'credentials:create',
    'credentials:update',
    'credentials:view',
    'datasets:create',
    'datasets:update',
    'datasets:view',
    'documentStores:add-loader',
    'documentStores:create',
    'documentStores:preview-process',
    'documentStores:update',
    'documentStores:upsert-config',
    'documentStores:view',
    'evaluations:create',
    'evaluations:run',
    'evaluations:view',
    'evaluators:create',
    'evaluators:update',
    'evaluators:view',
    'executions:view',
    'templates:custom',
    'templates:flowexport',
    'templates:marketplace',
    'templates:toolexport',
    'tools:create',
    'tools:export',
    'tools:update',
    'tools:view',
    'variables:create',
    'variables:update',
    'variables:view'
]

export const FLOWOPS_BUILTIN_ROLE_PERMISSION_ROWS = [
    ['owner', FLOWOPS_OWNER_ROLE_PERMISSIONS],
    ['admin', FLOWOPS_ADMIN_ROLE_PERMISSIONS],
    ['member', FLOWOPS_MEMBER_ROLE_PERMISSIONS]
] as const

export const toSqlStringLiteral = (value: unknown): string => JSON.stringify(value).replace(/'/g, "''")
