#!/usr/bin/env node

const fs = require('fs')
const path = require('path')
const { buildLocaleDictionary, collectFiles, transformSource } = require('./index')

const repoRoot = path.resolve(__dirname, '../..')
const defaultTargets = ['packages/ui/src/views', 'packages/ui/src/ui-component']

const toRelative = (file) => path.relative(repoRoot, file)

const auditFiles = (inputPaths = defaultTargets, { dictionary = buildLocaleDictionary() } = {}) => {
    const files = inputPaths.flatMap((inputPath) => collectFiles(path.resolve(repoRoot, inputPath))).sort()
    const results = []

    for (const file of files) {
        const source = fs.readFileSync(file, 'utf8')
        const result = transformSource(source, { dictionary, filename: toRelative(file) })
        if (result.changed || result.unmatchedText.length) {
            results.push({
                file: toRelative(file),
                replacements: result.replacements,
                unmatchedText: result.unmatchedText
            })
        }
    }

    return results
}

const renderReport = (results) => {
    const candidateCount = results.filter((result) => result.replacements > 0).length
    const unmatchedCount = results.filter((result) => result.unmatchedText.length > 0).length
    const lines = [
        '# i18n Residual English Audit',
        '',
        'Generated by `node scripts/i18n-codemod/audit.js --write-report`.',
        '',
        `- Files with locale-backed codemod candidates: ${candidateCount}`,
        `- Files with unmatched visible English text: ${unmatchedCount}`,
        '',
        '## Findings',
        ''
    ]

    if (results.length === 0) {
        lines.push('No residual JSX text or translatable JSX attributes were detected by the audit scanner.')
        return `${lines.join('\n').replace(/\n+$/g, '')}\n`
    }

    for (const result of results) {
        lines.push(`### \`${result.file}\``)
        lines.push('')
        if (result.replacements > 0) lines.push(`- Locale-backed codemod candidates: ${result.replacements}`)
        if (result.unmatchedText.length > 0) {
            lines.push('- Unmatched visible English:')
            for (const text of result.unmatchedText) {
                lines.push(`  - ${text.replace(/\|/g, '\\|')}`)
            }
        }
        lines.push('')
    }

    return `${lines.join('\n').replace(/\n+$/g, '')}\n`
}

const runCli = () => {
    const args = process.argv.slice(2)
    const writeReport = args.includes('--write-report')
    const failOnFindings = args.includes('--fail-on-findings')
    const targetPaths = args.filter((arg) => !arg.startsWith('--'))
    const results = auditFiles(targetPaths.length ? targetPaths : defaultTargets)
    const report = renderReport(results)

    if (writeReport) {
        fs.writeFileSync(path.join(__dirname, 'residual-english-report.md'), report)
    } else {
        process.stdout.write(report)
    }

    if (failOnFindings && results.length > 0) process.exit(1)
}

if (require.main === module) runCli()

module.exports = {
    auditFiles,
    renderReport
}
